//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  location: Location;
  locationConnection: LocationConnection;
  unitSize: UnitSize;
  unitSizeConnection: UnitSizeConnection;
  faqs: Faqs;
  faqsConnection: FaqsConnection;
  features: Features;
  featuresConnection: FeaturesConnection;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  aboutPage: AboutPage;
  aboutPageConnection: AboutPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryLocationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationFilter>;
};


export type QueryUnitSizeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUnitSizeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UnitSizeFilter>;
};


export type QueryFaqsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqsFilter>;
};


export type QueryFeaturesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeaturesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryAboutPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  location?: InputMaybe<LocationFilter>;
  unitSize?: InputMaybe<UnitSizeFilter>;
  faqs?: InputMaybe<FaqsFilter>;
  features?: InputMaybe<FeaturesFilter>;
  homePage?: InputMaybe<HomePageFilter>;
  aboutPage?: InputMaybe<AboutPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Location | UnitSize | Faqs | Features | HomePage | AboutPage | Folder;

export type SettingsSite = {
  __typename?: 'SettingsSite';
  legalName?: Maybe<Scalars['String']['output']>;
  brand?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SettingsContact = {
  __typename?: 'SettingsContact';
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
};

export type SettingsHours = {
  __typename?: 'SettingsHours';
  officeLabel?: Maybe<Scalars['String']['output']>;
  officeDetail?: Maybe<Scalars['String']['output']>;
  gateLabel?: Maybe<Scalars['String']['output']>;
  gateDetail?: Maybe<Scalars['String']['output']>;
};

export type SettingsPromo = {
  __typename?: 'SettingsPromo';
  headline?: Maybe<Scalars['String']['output']>;
  terms?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
  eyebrow?: Maybe<Scalars['String']['output']>;
  disclaimer?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  site?: Maybe<SettingsSite>;
  contact?: Maybe<SettingsContact>;
  hours?: Maybe<SettingsHours>;
  promo?: Maybe<SettingsPromo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsSiteFilter = {
  legalName?: InputMaybe<StringFilter>;
  brand?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SettingsContactFilter = {
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type SettingsHoursFilter = {
  officeLabel?: InputMaybe<StringFilter>;
  officeDetail?: InputMaybe<StringFilter>;
  gateLabel?: InputMaybe<StringFilter>;
  gateDetail?: InputMaybe<StringFilter>;
};

export type SettingsPromoFilter = {
  headline?: InputMaybe<StringFilter>;
  terms?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  site?: InputMaybe<SettingsSiteFilter>;
  contact?: InputMaybe<SettingsContactFilter>;
  hours?: InputMaybe<SettingsHoursFilter>;
  promo?: InputMaybe<SettingsPromoFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Location = Node & Document & {
  __typename?: 'Location';
  name?: Maybe<Scalars['String']['output']>;
  shortName?: Maybe<Scalars['String']['output']>;
  street?: Maybe<Scalars['String']['output']>;
  city?: Maybe<Scalars['String']['output']>;
  zip?: Maybe<Scalars['String']['output']>;
  blurb?: Maybe<Scalars['String']['output']>;
  areasServed?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocationFilter = {
  name?: InputMaybe<StringFilter>;
  shortName?: InputMaybe<StringFilter>;
  street?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  zip?: InputMaybe<StringFilter>;
  blurb?: InputMaybe<StringFilter>;
  areasServed?: InputMaybe<StringFilter>;
};

export type LocationConnectionEdges = {
  __typename?: 'LocationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Location>;
};

export type LocationConnection = Connection & {
  __typename?: 'LocationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocationConnectionEdges>>>;
};

export type UnitSize = Node & Document & {
  __typename?: 'UnitSize';
  label?: Maybe<Scalars['String']['output']>;
  dims?: Maybe<Scalars['String']['output']>;
  area?: Maybe<Scalars['Float']['output']>;
  monthly?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  idealFor?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type UnitSizeFilter = {
  label?: InputMaybe<StringFilter>;
  dims?: InputMaybe<StringFilter>;
  area?: InputMaybe<NumberFilter>;
  monthly?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  idealFor?: InputMaybe<StringFilter>;
};

export type UnitSizeConnectionEdges = {
  __typename?: 'UnitSizeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<UnitSize>;
};

export type UnitSizeConnection = Connection & {
  __typename?: 'UnitSizeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UnitSizeConnectionEdges>>>;
};

export type FaqsItems = {
  __typename?: 'FaqsItems';
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Faqs = Node & Document & {
  __typename?: 'Faqs';
  items?: Maybe<Array<Maybe<FaqsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqsItemsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type FaqsFilter = {
  items?: InputMaybe<FaqsItemsFilter>;
};

export type FaqsConnectionEdges = {
  __typename?: 'FaqsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faqs>;
};

export type FaqsConnection = Connection & {
  __typename?: 'FaqsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqsConnectionEdges>>>;
};

export type Features = Node & Document & {
  __typename?: 'Features';
  pageHeading?: Maybe<Scalars['String']['output']>;
  pageSubheading?: Maybe<Scalars['String']['output']>;
  securityIntro?: Maybe<Scalars['String']['output']>;
  accessIntro?: Maybe<Scalars['String']['output']>;
  convenienceIntro?: Maybe<Scalars['String']['output']>;
  cameraHeading?: Maybe<Scalars['String']['output']>;
  cameraParagraph1?: Maybe<Scalars['String']['output']>;
  cameraParagraph2?: Maybe<Scalars['String']['output']>;
  cameraParagraph3?: Maybe<Scalars['String']['output']>;
  security?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  access?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  convenience?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeaturesFilter = {
  pageHeading?: InputMaybe<StringFilter>;
  pageSubheading?: InputMaybe<StringFilter>;
  securityIntro?: InputMaybe<StringFilter>;
  accessIntro?: InputMaybe<StringFilter>;
  convenienceIntro?: InputMaybe<StringFilter>;
  cameraHeading?: InputMaybe<StringFilter>;
  cameraParagraph1?: InputMaybe<StringFilter>;
  cameraParagraph2?: InputMaybe<StringFilter>;
  cameraParagraph3?: InputMaybe<StringFilter>;
  security?: InputMaybe<StringFilter>;
  access?: InputMaybe<StringFilter>;
  convenience?: InputMaybe<StringFilter>;
};

export type FeaturesConnectionEdges = {
  __typename?: 'FeaturesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Features>;
};

export type FeaturesConnection = Connection & {
  __typename?: 'FeaturesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeaturesConnectionEdges>>>;
};

export type HomePageHero = {
  __typename?: 'HomePageHero';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomePageProofPointsCards = {
  __typename?: 'HomePageProofPointsCards';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomePageProofPoints = {
  __typename?: 'HomePageProofPoints';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HomePageProofPointsCards>>>;
};

export type HomePagePricing = {
  __typename?: 'HomePagePricing';
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  footerNote?: Maybe<Scalars['String']['output']>;
  smallSubtitle?: Maybe<Scalars['String']['output']>;
  smallFits?: Maybe<Scalars['String']['output']>;
  mediumSubtitle?: Maybe<Scalars['String']['output']>;
  mediumFits?: Maybe<Scalars['String']['output']>;
  largeSubtitle?: Maybe<Scalars['String']['output']>;
  largeFits?: Maybe<Scalars['String']['output']>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  hero?: Maybe<HomePageHero>;
  proofPoints?: Maybe<HomePageProofPoints>;
  pricing?: Maybe<HomePagePricing>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomePageHeroFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<StringFilter>;
};

export type HomePageProofPointsCardsFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomePageProofPointsFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HomePageProofPointsCardsFilter>;
};

export type HomePagePricingFilter = {
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  footerNote?: InputMaybe<StringFilter>;
  smallSubtitle?: InputMaybe<StringFilter>;
  smallFits?: InputMaybe<StringFilter>;
  mediumSubtitle?: InputMaybe<StringFilter>;
  mediumFits?: InputMaybe<StringFilter>;
  largeSubtitle?: InputMaybe<StringFilter>;
  largeFits?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  hero?: InputMaybe<HomePageHeroFilter>;
  proofPoints?: InputMaybe<HomePageProofPointsFilter>;
  pricing?: InputMaybe<HomePagePricingFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type AboutPageValues = {
  __typename?: 'AboutPageValues';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type AboutPage = Node & Document & {
  __typename?: 'AboutPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubheading?: Maybe<Scalars['String']['output']>;
  whyHeading?: Maybe<Scalars['String']['output']>;
  whyParagraph1?: Maybe<Scalars['String']['output']>;
  whyParagraph2?: Maybe<Scalars['String']['output']>;
  careHeading?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<AboutPageValues>>>;
  whereHeading?: Maybe<Scalars['String']['output']>;
  whereBody?: Maybe<Scalars['String']['output']>;
  getInTouchHeading?: Maybe<Scalars['String']['output']>;
  getInTouchBody?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutPageValuesFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type AboutPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubheading?: InputMaybe<StringFilter>;
  whyHeading?: InputMaybe<StringFilter>;
  whyParagraph1?: InputMaybe<StringFilter>;
  whyParagraph2?: InputMaybe<StringFilter>;
  careHeading?: InputMaybe<StringFilter>;
  values?: InputMaybe<AboutPageValuesFilter>;
  whereHeading?: InputMaybe<StringFilter>;
  whereBody?: InputMaybe<StringFilter>;
  getInTouchHeading?: InputMaybe<StringFilter>;
  getInTouchBody?: InputMaybe<StringFilter>;
};

export type AboutPageConnectionEdges = {
  __typename?: 'AboutPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<AboutPage>;
};

export type AboutPageConnection = Connection & {
  __typename?: 'AboutPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateLocation: Location;
  createLocation: Location;
  updateUnitSize: UnitSize;
  createUnitSize: UnitSize;
  updateFaqs: Faqs;
  createFaqs: Faqs;
  updateFeatures: Features;
  createFeatures: Features;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateAboutPage: AboutPage;
  createAboutPage: AboutPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationCreateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationUpdateUnitSizeArgs = {
  relativePath: Scalars['String']['input'];
  params: UnitSizeMutation;
};


export type MutationCreateUnitSizeArgs = {
  relativePath: Scalars['String']['input'];
  params: UnitSizeMutation;
};


export type MutationUpdateFaqsArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqsMutation;
};


export type MutationCreateFaqsArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqsMutation;
};


export type MutationUpdateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationCreateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};


export type MutationCreateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  location?: InputMaybe<LocationMutation>;
  unitSize?: InputMaybe<UnitSizeMutation>;
  faqs?: InputMaybe<FaqsMutation>;
  features?: InputMaybe<FeaturesMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  location?: InputMaybe<LocationMutation>;
  unitSize?: InputMaybe<UnitSizeMutation>;
  faqs?: InputMaybe<FaqsMutation>;
  features?: InputMaybe<FeaturesMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
};

export type SettingsSiteMutation = {
  legalName?: InputMaybe<Scalars['String']['input']>;
  brand?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsContactMutation = {
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsHoursMutation = {
  officeLabel?: InputMaybe<Scalars['String']['input']>;
  officeDetail?: InputMaybe<Scalars['String']['input']>;
  gateLabel?: InputMaybe<Scalars['String']['input']>;
  gateDetail?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsPromoMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  terms?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  disclaimer?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  site?: InputMaybe<SettingsSiteMutation>;
  contact?: InputMaybe<SettingsContactMutation>;
  hours?: InputMaybe<SettingsHoursMutation>;
  promo?: InputMaybe<SettingsPromoMutation>;
};

export type LocationMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  shortName?: InputMaybe<Scalars['String']['input']>;
  street?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  zip?: InputMaybe<Scalars['String']['input']>;
  blurb?: InputMaybe<Scalars['String']['input']>;
  areasServed?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type UnitSizeMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  dims?: InputMaybe<Scalars['String']['input']>;
  area?: InputMaybe<Scalars['Float']['input']>;
  monthly?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  idealFor?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FaqsItemsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type FaqsMutation = {
  items?: InputMaybe<Array<InputMaybe<FaqsItemsMutation>>>;
};

export type FeaturesMutation = {
  pageHeading?: InputMaybe<Scalars['String']['input']>;
  pageSubheading?: InputMaybe<Scalars['String']['input']>;
  securityIntro?: InputMaybe<Scalars['String']['input']>;
  accessIntro?: InputMaybe<Scalars['String']['input']>;
  convenienceIntro?: InputMaybe<Scalars['String']['input']>;
  cameraHeading?: InputMaybe<Scalars['String']['input']>;
  cameraParagraph1?: InputMaybe<Scalars['String']['input']>;
  cameraParagraph2?: InputMaybe<Scalars['String']['input']>;
  cameraParagraph3?: InputMaybe<Scalars['String']['input']>;
  security?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  access?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  convenience?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageHeroMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageProofPointsCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageProofPointsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HomePageProofPointsCardsMutation>>>;
};

export type HomePagePricingMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
  smallSubtitle?: InputMaybe<Scalars['String']['input']>;
  smallFits?: InputMaybe<Scalars['String']['input']>;
  mediumSubtitle?: InputMaybe<Scalars['String']['input']>;
  mediumFits?: InputMaybe<Scalars['String']['input']>;
  largeSubtitle?: InputMaybe<Scalars['String']['input']>;
  largeFits?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMutation = {
  hero?: InputMaybe<HomePageHeroMutation>;
  proofPoints?: InputMaybe<HomePageProofPointsMutation>;
  pricing?: InputMaybe<HomePagePricingMutation>;
};

export type AboutPageValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type AboutPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubheading?: InputMaybe<Scalars['String']['input']>;
  whyHeading?: InputMaybe<Scalars['String']['input']>;
  whyParagraph1?: InputMaybe<Scalars['String']['input']>;
  whyParagraph2?: InputMaybe<Scalars['String']['input']>;
  careHeading?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<AboutPageValuesMutation>>>;
  whereHeading?: InputMaybe<Scalars['String']['input']>;
  whereBody?: InputMaybe<Scalars['String']['input']>;
  getInTouchHeading?: InputMaybe<Scalars['String']['input']>;
  getInTouchBody?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsPartsFragment = { __typename: 'Settings', site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null, eyebrow?: string | null, disclaimer?: string | null } | null };

export type LocationPartsFragment = { __typename: 'Location', name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null };

export type UnitSizePartsFragment = { __typename: 'UnitSize', label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null };

export type FaqsPartsFragment = { __typename: 'Faqs', items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null };

export type FeaturesPartsFragment = { __typename: 'Features', pageHeading?: string | null, pageSubheading?: string | null, securityIntro?: string | null, accessIntro?: string | null, convenienceIntro?: string | null, cameraHeading?: string | null, cameraParagraph1?: string | null, cameraParagraph2?: string | null, cameraParagraph3?: string | null, security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null };

export type HomePagePartsFragment = { __typename: 'HomePage', hero?: { __typename: 'HomePageHero', heading?: string | null, subheading?: string | null, highlights?: Array<string | null> | null } | null, proofPoints?: { __typename: 'HomePageProofPoints', heading?: string | null, subheading?: string | null, cards?: Array<{ __typename: 'HomePageProofPointsCards', title?: string | null, body?: string | null } | null> | null } | null, pricing?: { __typename: 'HomePagePricing', heading?: string | null, subheading?: string | null, footerNote?: string | null, smallSubtitle?: string | null, smallFits?: string | null, mediumSubtitle?: string | null, mediumFits?: string | null, largeSubtitle?: string | null, largeFits?: string | null } | null };

export type AboutPagePartsFragment = { __typename: 'AboutPage', heroHeading?: string | null, heroSubheading?: string | null, whyHeading?: string | null, whyParagraph1?: string | null, whyParagraph2?: string | null, careHeading?: string | null, whereHeading?: string | null, whereBody?: string | null, getInTouchHeading?: string | null, getInTouchBody?: string | null, values?: Array<{ __typename: 'AboutPageValues', title?: string | null, body?: string | null } | null> | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null, eyebrow?: string | null, disclaimer?: string | null } | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null, eyebrow?: string | null, disclaimer?: string | null } | null } | null } | null> | null } };

export type LocationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LocationQuery = { __typename?: 'Query', location: { __typename: 'Location', id: string, name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LocationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationFilter>;
}>;


export type LocationConnectionQuery = { __typename?: 'Query', locationConnection: { __typename?: 'LocationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LocationConnectionEdges', cursor: string, node?: { __typename: 'Location', id: string, name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type UnitSizeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type UnitSizeQuery = { __typename?: 'Query', unitSize: { __typename: 'UnitSize', id: string, label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type UnitSizeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UnitSizeFilter>;
}>;


export type UnitSizeConnectionQuery = { __typename?: 'Query', unitSizeConnection: { __typename?: 'UnitSizeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'UnitSizeConnectionEdges', cursor: string, node?: { __typename: 'UnitSize', id: string, label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqsQuery = { __typename?: 'Query', faqs: { __typename: 'Faqs', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null } };

export type FaqsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqsFilter>;
}>;


export type FaqsConnectionQuery = { __typename?: 'Query', faqsConnection: { __typename?: 'FaqsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqsConnectionEdges', cursor: string, node?: { __typename: 'Faqs', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null } | null } | null> | null } };

export type FeaturesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeaturesQuery = { __typename?: 'Query', features: { __typename: 'Features', id: string, pageHeading?: string | null, pageSubheading?: string | null, securityIntro?: string | null, accessIntro?: string | null, convenienceIntro?: string | null, cameraHeading?: string | null, cameraParagraph1?: string | null, cameraParagraph2?: string | null, cameraParagraph3?: string | null, security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FeaturesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
}>;


export type FeaturesConnectionQuery = { __typename?: 'Query', featuresConnection: { __typename?: 'FeaturesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeaturesConnectionEdges', cursor: string, node?: { __typename: 'Features', id: string, pageHeading?: string | null, pageSubheading?: string | null, securityIntro?: string | null, accessIntro?: string | null, convenienceIntro?: string | null, cameraHeading?: string | null, cameraParagraph1?: string | null, cameraParagraph2?: string | null, cameraParagraph3?: string | null, security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', heading?: string | null, subheading?: string | null, highlights?: Array<string | null> | null } | null, proofPoints?: { __typename: 'HomePageProofPoints', heading?: string | null, subheading?: string | null, cards?: Array<{ __typename: 'HomePageProofPointsCards', title?: string | null, body?: string | null } | null> | null } | null, pricing?: { __typename: 'HomePagePricing', heading?: string | null, subheading?: string | null, footerNote?: string | null, smallSubtitle?: string | null, smallFits?: string | null, mediumSubtitle?: string | null, mediumFits?: string | null, largeSubtitle?: string | null, largeFits?: string | null } | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomePageHero', heading?: string | null, subheading?: string | null, highlights?: Array<string | null> | null } | null, proofPoints?: { __typename: 'HomePageProofPoints', heading?: string | null, subheading?: string | null, cards?: Array<{ __typename: 'HomePageProofPointsCards', title?: string | null, body?: string | null } | null> | null } | null, pricing?: { __typename: 'HomePagePricing', heading?: string | null, subheading?: string | null, footerNote?: string | null, smallSubtitle?: string | null, smallFits?: string | null, mediumSubtitle?: string | null, mediumFits?: string | null, largeSubtitle?: string | null, largeFits?: string | null } | null } | null } | null> | null } };

export type AboutPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutPageQuery = { __typename?: 'Query', aboutPage: { __typename: 'AboutPage', id: string, heroHeading?: string | null, heroSubheading?: string | null, whyHeading?: string | null, whyParagraph1?: string | null, whyParagraph2?: string | null, careHeading?: string | null, whereHeading?: string | null, whereBody?: string | null, getInTouchHeading?: string | null, getInTouchBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', title?: string | null, body?: string | null } | null> | null } };

export type AboutPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
}>;


export type AboutPageConnectionQuery = { __typename?: 'Query', aboutPageConnection: { __typename?: 'AboutPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutPageConnectionEdges', cursor: string, node?: { __typename: 'AboutPage', id: string, heroHeading?: string | null, heroSubheading?: string | null, whyHeading?: string | null, whyParagraph1?: string | null, whyParagraph2?: string | null, careHeading?: string | null, whereHeading?: string | null, whereBody?: string | null, getInTouchHeading?: string | null, getInTouchBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', title?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  site {
    __typename
    legalName
    brand
    tagline
    description
  }
  contact {
    __typename
    phone
    email
  }
  hours {
    __typename
    officeLabel
    officeDetail
    gateLabel
    gateDetail
  }
  promo {
    __typename
    headline
    terms
    details
    eyebrow
    disclaimer
  }
}
    `;
export const LocationPartsFragmentDoc = gql`
    fragment LocationParts on Location {
  __typename
  name
  shortName
  street
  city
  zip
  blurb
  areasServed
}
    `;
export const UnitSizePartsFragmentDoc = gql`
    fragment UnitSizeParts on UnitSize {
  __typename
  label
  dims
  area
  monthly
  description
  features
  idealFor
}
    `;
export const FaqsPartsFragmentDoc = gql`
    fragment FaqsParts on Faqs {
  __typename
  items {
    __typename
    q
    a
  }
}
    `;
export const FeaturesPartsFragmentDoc = gql`
    fragment FeaturesParts on Features {
  __typename
  pageHeading
  pageSubheading
  securityIntro
  accessIntro
  convenienceIntro
  cameraHeading
  cameraParagraph1
  cameraParagraph2
  cameraParagraph3
  security
  access
  convenience
}
    `;
export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  hero {
    __typename
    heading
    subheading
    highlights
  }
  proofPoints {
    __typename
    heading
    subheading
    cards {
      __typename
      title
      body
    }
  }
  pricing {
    __typename
    heading
    subheading
    footerNote
    smallSubtitle
    smallFits
    mediumSubtitle
    mediumFits
    largeSubtitle
    largeFits
  }
}
    `;
export const AboutPagePartsFragmentDoc = gql`
    fragment AboutPageParts on AboutPage {
  __typename
  heroHeading
  heroSubheading
  whyHeading
  whyParagraph1
  whyParagraph2
  careHeading
  values {
    __typename
    title
    body
  }
  whereHeading
  whereBody
  getInTouchHeading
  getInTouchBody
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const LocationDocument = gql`
    query location($relativePath: String!) {
  location(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocationParts
  }
}
    ${LocationPartsFragmentDoc}`;
export const LocationConnectionDocument = gql`
    query locationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocationFilter) {
  locationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocationParts
      }
    }
  }
}
    ${LocationPartsFragmentDoc}`;
export const UnitSizeDocument = gql`
    query unitSize($relativePath: String!) {
  unitSize(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UnitSizeParts
  }
}
    ${UnitSizePartsFragmentDoc}`;
export const UnitSizeConnectionDocument = gql`
    query unitSizeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UnitSizeFilter) {
  unitSizeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UnitSizeParts
      }
    }
  }
}
    ${UnitSizePartsFragmentDoc}`;
export const FaqsDocument = gql`
    query faqs($relativePath: String!) {
  faqs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqsParts
  }
}
    ${FaqsPartsFragmentDoc}`;
export const FaqsConnectionDocument = gql`
    query faqsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqsFilter) {
  faqsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqsParts
      }
    }
  }
}
    ${FaqsPartsFragmentDoc}`;
export const FeaturesDocument = gql`
    query features($relativePath: String!) {
  features(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeaturesParts
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const FeaturesConnectionDocument = gql`
    query featuresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeaturesFilter) {
  featuresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeaturesParts
      }
    }
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const AboutPageDocument = gql`
    query aboutPage($relativePath: String!) {
  aboutPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutPageParts
  }
}
    ${AboutPagePartsFragmentDoc}`;
export const AboutPageConnectionDocument = gql`
    query aboutPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutPageFilter) {
  aboutPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutPageParts
      }
    }
  }
}
    ${AboutPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    location(variables: LocationQueryVariables, options?: C): Promise<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}> {
        return requester<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}, LocationQueryVariables>(LocationDocument, variables, options);
      },
    locationConnection(variables?: LocationConnectionQueryVariables, options?: C): Promise<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}> {
        return requester<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}, LocationConnectionQueryVariables>(LocationConnectionDocument, variables, options);
      },
    unitSize(variables: UnitSizeQueryVariables, options?: C): Promise<{data: UnitSizeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeQueryVariables, query: string}> {
        return requester<{data: UnitSizeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeQueryVariables, query: string}, UnitSizeQueryVariables>(UnitSizeDocument, variables, options);
      },
    unitSizeConnection(variables?: UnitSizeConnectionQueryVariables, options?: C): Promise<{data: UnitSizeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeConnectionQueryVariables, query: string}> {
        return requester<{data: UnitSizeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeConnectionQueryVariables, query: string}, UnitSizeConnectionQueryVariables>(UnitSizeConnectionDocument, variables, options);
      },
    faqs(variables: FaqsQueryVariables, options?: C): Promise<{data: FaqsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsQueryVariables, query: string}> {
        return requester<{data: FaqsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsQueryVariables, query: string}, FaqsQueryVariables>(FaqsDocument, variables, options);
      },
    faqsConnection(variables?: FaqsConnectionQueryVariables, options?: C): Promise<{data: FaqsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsConnectionQueryVariables, query: string}> {
        return requester<{data: FaqsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsConnectionQueryVariables, query: string}, FaqsConnectionQueryVariables>(FaqsConnectionDocument, variables, options);
      },
    features(variables: FeaturesQueryVariables, options?: C): Promise<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}> {
        return requester<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}, FeaturesQueryVariables>(FeaturesDocument, variables, options);
      },
    featuresConnection(variables?: FeaturesConnectionQueryVariables, options?: C): Promise<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}> {
        return requester<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}, FeaturesConnectionQueryVariables>(FeaturesConnectionDocument, variables, options);
      },
    homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    aboutPage(variables: AboutPageQueryVariables, options?: C): Promise<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}> {
        return requester<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}, AboutPageQueryVariables>(AboutPageDocument, variables, options);
      },
    aboutPageConnection(variables?: AboutPageConnectionQueryVariables, options?: C): Promise<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}> {
        return requester<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}, AboutPageConnectionQueryVariables>(AboutPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  