//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  location: Location;
  locationConnection: LocationConnection;
  unitSize: UnitSize;
  unitSizeConnection: UnitSizeConnection;
  faqs: Faqs;
  faqsConnection: FaqsConnection;
  features: Features;
  featuresConnection: FeaturesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryLocationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationFilter>;
};


export type QueryUnitSizeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUnitSizeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UnitSizeFilter>;
};


export type QueryFaqsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqsFilter>;
};


export type QueryFeaturesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeaturesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  location?: InputMaybe<LocationFilter>;
  unitSize?: InputMaybe<UnitSizeFilter>;
  faqs?: InputMaybe<FaqsFilter>;
  features?: InputMaybe<FeaturesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Location | UnitSize | Faqs | Features | Folder;

export type SettingsSite = {
  __typename?: 'SettingsSite';
  legalName?: Maybe<Scalars['String']['output']>;
  brand?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SettingsContact = {
  __typename?: 'SettingsContact';
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
};

export type SettingsHours = {
  __typename?: 'SettingsHours';
  officeLabel?: Maybe<Scalars['String']['output']>;
  officeDetail?: Maybe<Scalars['String']['output']>;
  gateLabel?: Maybe<Scalars['String']['output']>;
  gateDetail?: Maybe<Scalars['String']['output']>;
};

export type SettingsPromo = {
  __typename?: 'SettingsPromo';
  headline?: Maybe<Scalars['String']['output']>;
  terms?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  site?: Maybe<SettingsSite>;
  contact?: Maybe<SettingsContact>;
  hours?: Maybe<SettingsHours>;
  promo?: Maybe<SettingsPromo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsSiteFilter = {
  legalName?: InputMaybe<StringFilter>;
  brand?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SettingsContactFilter = {
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type SettingsHoursFilter = {
  officeLabel?: InputMaybe<StringFilter>;
  officeDetail?: InputMaybe<StringFilter>;
  gateLabel?: InputMaybe<StringFilter>;
  gateDetail?: InputMaybe<StringFilter>;
};

export type SettingsPromoFilter = {
  headline?: InputMaybe<StringFilter>;
  terms?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  site?: InputMaybe<SettingsSiteFilter>;
  contact?: InputMaybe<SettingsContactFilter>;
  hours?: InputMaybe<SettingsHoursFilter>;
  promo?: InputMaybe<SettingsPromoFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Location = Node & Document & {
  __typename?: 'Location';
  name?: Maybe<Scalars['String']['output']>;
  shortName?: Maybe<Scalars['String']['output']>;
  street?: Maybe<Scalars['String']['output']>;
  city?: Maybe<Scalars['String']['output']>;
  zip?: Maybe<Scalars['String']['output']>;
  blurb?: Maybe<Scalars['String']['output']>;
  areasServed?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocationFilter = {
  name?: InputMaybe<StringFilter>;
  shortName?: InputMaybe<StringFilter>;
  street?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  zip?: InputMaybe<StringFilter>;
  blurb?: InputMaybe<StringFilter>;
  areasServed?: InputMaybe<StringFilter>;
};

export type LocationConnectionEdges = {
  __typename?: 'LocationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Location>;
};

export type LocationConnection = Connection & {
  __typename?: 'LocationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocationConnectionEdges>>>;
};

export type UnitSize = Node & Document & {
  __typename?: 'UnitSize';
  label?: Maybe<Scalars['String']['output']>;
  dims?: Maybe<Scalars['String']['output']>;
  area?: Maybe<Scalars['Float']['output']>;
  monthly?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  idealFor?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type UnitSizeFilter = {
  label?: InputMaybe<StringFilter>;
  dims?: InputMaybe<StringFilter>;
  area?: InputMaybe<NumberFilter>;
  monthly?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  idealFor?: InputMaybe<StringFilter>;
};

export type UnitSizeConnectionEdges = {
  __typename?: 'UnitSizeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<UnitSize>;
};

export type UnitSizeConnection = Connection & {
  __typename?: 'UnitSizeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UnitSizeConnectionEdges>>>;
};

export type FaqsItems = {
  __typename?: 'FaqsItems';
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Faqs = Node & Document & {
  __typename?: 'Faqs';
  items?: Maybe<Array<Maybe<FaqsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqsItemsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type FaqsFilter = {
  items?: InputMaybe<FaqsItemsFilter>;
};

export type FaqsConnectionEdges = {
  __typename?: 'FaqsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faqs>;
};

export type FaqsConnection = Connection & {
  __typename?: 'FaqsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqsConnectionEdges>>>;
};

export type Features = Node & Document & {
  __typename?: 'Features';
  security?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  access?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  convenience?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeaturesFilter = {
  security?: InputMaybe<StringFilter>;
  access?: InputMaybe<StringFilter>;
  convenience?: InputMaybe<StringFilter>;
};

export type FeaturesConnectionEdges = {
  __typename?: 'FeaturesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Features>;
};

export type FeaturesConnection = Connection & {
  __typename?: 'FeaturesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeaturesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateLocation: Location;
  createLocation: Location;
  updateUnitSize: UnitSize;
  createUnitSize: UnitSize;
  updateFaqs: Faqs;
  createFaqs: Faqs;
  updateFeatures: Features;
  createFeatures: Features;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationCreateLocationArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationMutation;
};


export type MutationUpdateUnitSizeArgs = {
  relativePath: Scalars['String']['input'];
  params: UnitSizeMutation;
};


export type MutationCreateUnitSizeArgs = {
  relativePath: Scalars['String']['input'];
  params: UnitSizeMutation;
};


export type MutationUpdateFaqsArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqsMutation;
};


export type MutationCreateFaqsArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqsMutation;
};


export type MutationUpdateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationCreateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  location?: InputMaybe<LocationMutation>;
  unitSize?: InputMaybe<UnitSizeMutation>;
  faqs?: InputMaybe<FaqsMutation>;
  features?: InputMaybe<FeaturesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  location?: InputMaybe<LocationMutation>;
  unitSize?: InputMaybe<UnitSizeMutation>;
  faqs?: InputMaybe<FaqsMutation>;
  features?: InputMaybe<FeaturesMutation>;
};

export type SettingsSiteMutation = {
  legalName?: InputMaybe<Scalars['String']['input']>;
  brand?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsContactMutation = {
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsHoursMutation = {
  officeLabel?: InputMaybe<Scalars['String']['input']>;
  officeDetail?: InputMaybe<Scalars['String']['input']>;
  gateLabel?: InputMaybe<Scalars['String']['input']>;
  gateDetail?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsPromoMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  terms?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  site?: InputMaybe<SettingsSiteMutation>;
  contact?: InputMaybe<SettingsContactMutation>;
  hours?: InputMaybe<SettingsHoursMutation>;
  promo?: InputMaybe<SettingsPromoMutation>;
};

export type LocationMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  shortName?: InputMaybe<Scalars['String']['input']>;
  street?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  zip?: InputMaybe<Scalars['String']['input']>;
  blurb?: InputMaybe<Scalars['String']['input']>;
  areasServed?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type UnitSizeMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  dims?: InputMaybe<Scalars['String']['input']>;
  area?: InputMaybe<Scalars['Float']['input']>;
  monthly?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  idealFor?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FaqsItemsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type FaqsMutation = {
  items?: InputMaybe<Array<InputMaybe<FaqsItemsMutation>>>;
};

export type FeaturesMutation = {
  security?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  access?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  convenience?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsPartsFragment = { __typename: 'Settings', site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null } | null };

export type LocationPartsFragment = { __typename: 'Location', name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null };

export type UnitSizePartsFragment = { __typename: 'UnitSize', label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null };

export type FaqsPartsFragment = { __typename: 'Faqs', items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null };

export type FeaturesPartsFragment = { __typename: 'Features', security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null } | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, site?: { __typename: 'SettingsSite', legalName?: string | null, brand?: string | null, tagline?: string | null, description?: string | null } | null, contact?: { __typename: 'SettingsContact', phone?: string | null, email?: string | null } | null, hours?: { __typename: 'SettingsHours', officeLabel?: string | null, officeDetail?: string | null, gateLabel?: string | null, gateDetail?: string | null } | null, promo?: { __typename: 'SettingsPromo', headline?: string | null, terms?: string | null, details?: string | null } | null } | null } | null> | null } };

export type LocationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LocationQuery = { __typename?: 'Query', location: { __typename: 'Location', id: string, name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LocationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationFilter>;
}>;


export type LocationConnectionQuery = { __typename?: 'Query', locationConnection: { __typename?: 'LocationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LocationConnectionEdges', cursor: string, node?: { __typename: 'Location', id: string, name?: string | null, shortName?: string | null, street?: string | null, city?: string | null, zip?: string | null, blurb?: string | null, areasServed?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type UnitSizeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type UnitSizeQuery = { __typename?: 'Query', unitSize: { __typename: 'UnitSize', id: string, label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type UnitSizeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UnitSizeFilter>;
}>;


export type UnitSizeConnectionQuery = { __typename?: 'Query', unitSizeConnection: { __typename?: 'UnitSizeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'UnitSizeConnectionEdges', cursor: string, node?: { __typename: 'UnitSize', id: string, label?: string | null, dims?: string | null, area?: number | null, monthly?: number | null, description?: string | null, features?: Array<string | null> | null, idealFor?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqsQuery = { __typename?: 'Query', faqs: { __typename: 'Faqs', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null } };

export type FaqsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqsFilter>;
}>;


export type FaqsConnectionQuery = { __typename?: 'Query', faqsConnection: { __typename?: 'FaqsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqsConnectionEdges', cursor: string, node?: { __typename: 'Faqs', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqsItems', q?: string | null, a?: string | null } | null> | null } | null } | null> | null } };

export type FeaturesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeaturesQuery = { __typename?: 'Query', features: { __typename: 'Features', id: string, security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FeaturesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
}>;


export type FeaturesConnectionQuery = { __typename?: 'Query', featuresConnection: { __typename?: 'FeaturesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeaturesConnectionEdges', cursor: string, node?: { __typename: 'Features', id: string, security?: Array<string | null> | null, access?: Array<string | null> | null, convenience?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  site {
    __typename
    legalName
    brand
    tagline
    description
  }
  contact {
    __typename
    phone
    email
  }
  hours {
    __typename
    officeLabel
    officeDetail
    gateLabel
    gateDetail
  }
  promo {
    __typename
    headline
    terms
    details
  }
}
    `;
export const LocationPartsFragmentDoc = gql`
    fragment LocationParts on Location {
  __typename
  name
  shortName
  street
  city
  zip
  blurb
  areasServed
}
    `;
export const UnitSizePartsFragmentDoc = gql`
    fragment UnitSizeParts on UnitSize {
  __typename
  label
  dims
  area
  monthly
  description
  features
  idealFor
}
    `;
export const FaqsPartsFragmentDoc = gql`
    fragment FaqsParts on Faqs {
  __typename
  items {
    __typename
    q
    a
  }
}
    `;
export const FeaturesPartsFragmentDoc = gql`
    fragment FeaturesParts on Features {
  __typename
  security
  access
  convenience
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const LocationDocument = gql`
    query location($relativePath: String!) {
  location(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocationParts
  }
}
    ${LocationPartsFragmentDoc}`;
export const LocationConnectionDocument = gql`
    query locationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocationFilter) {
  locationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocationParts
      }
    }
  }
}
    ${LocationPartsFragmentDoc}`;
export const UnitSizeDocument = gql`
    query unitSize($relativePath: String!) {
  unitSize(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UnitSizeParts
  }
}
    ${UnitSizePartsFragmentDoc}`;
export const UnitSizeConnectionDocument = gql`
    query unitSizeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UnitSizeFilter) {
  unitSizeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UnitSizeParts
      }
    }
  }
}
    ${UnitSizePartsFragmentDoc}`;
export const FaqsDocument = gql`
    query faqs($relativePath: String!) {
  faqs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqsParts
  }
}
    ${FaqsPartsFragmentDoc}`;
export const FaqsConnectionDocument = gql`
    query faqsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqsFilter) {
  faqsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqsParts
      }
    }
  }
}
    ${FaqsPartsFragmentDoc}`;
export const FeaturesDocument = gql`
    query features($relativePath: String!) {
  features(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeaturesParts
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const FeaturesConnectionDocument = gql`
    query featuresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeaturesFilter) {
  featuresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeaturesParts
      }
    }
  }
}
    ${FeaturesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    location(variables: LocationQueryVariables, options?: C): Promise<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}> {
        return requester<{data: LocationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationQueryVariables, query: string}, LocationQueryVariables>(LocationDocument, variables, options);
      },
    locationConnection(variables?: LocationConnectionQueryVariables, options?: C): Promise<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}> {
        return requester<{data: LocationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationConnectionQueryVariables, query: string}, LocationConnectionQueryVariables>(LocationConnectionDocument, variables, options);
      },
    unitSize(variables: UnitSizeQueryVariables, options?: C): Promise<{data: UnitSizeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeQueryVariables, query: string}> {
        return requester<{data: UnitSizeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeQueryVariables, query: string}, UnitSizeQueryVariables>(UnitSizeDocument, variables, options);
      },
    unitSizeConnection(variables?: UnitSizeConnectionQueryVariables, options?: C): Promise<{data: UnitSizeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeConnectionQueryVariables, query: string}> {
        return requester<{data: UnitSizeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UnitSizeConnectionQueryVariables, query: string}, UnitSizeConnectionQueryVariables>(UnitSizeConnectionDocument, variables, options);
      },
    faqs(variables: FaqsQueryVariables, options?: C): Promise<{data: FaqsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsQueryVariables, query: string}> {
        return requester<{data: FaqsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsQueryVariables, query: string}, FaqsQueryVariables>(FaqsDocument, variables, options);
      },
    faqsConnection(variables?: FaqsConnectionQueryVariables, options?: C): Promise<{data: FaqsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsConnectionQueryVariables, query: string}> {
        return requester<{data: FaqsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqsConnectionQueryVariables, query: string}, FaqsConnectionQueryVariables>(FaqsConnectionDocument, variables, options);
      },
    features(variables: FeaturesQueryVariables, options?: C): Promise<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}> {
        return requester<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}, FeaturesQueryVariables>(FeaturesDocument, variables, options);
      },
    featuresConnection(variables?: FeaturesConnectionQueryVariables, options?: C): Promise<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}> {
        return requester<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}, FeaturesConnectionQueryVariables>(FeaturesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/76790464-d1a9-489b-9440-210905865f36/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  